name: taskou_pro
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.1
  connectivity_plus: ^3.0.2
  country_picker: ^2.0.19
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  firebase_messaging: ^14.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_image_compress: ^1.1.3
  flutter_local_notifications: ^14.1.0
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.6
  in_app_update: ^4.0.1
  intl: ^0.17.0
  location: ^4.4.0
  mapbox_search: ^3.0.1+2
  package_info_plus: ^3.1.2
  path_provider: ^2.0.11
  pinput: ^2.2.21
  reactive_forms: ^14.1.0
  share_plus: ^6.3.0
  table_calendar: ^3.0.8
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  video_compress: 3.1.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
