// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZQKlUn6FiBoxnBAfelakOPZ7qFEld3M',
    appId: '1:616490055606:web:8949400ec64884fb7f7317',
    messagingSenderId: '616490055606',
    projectId: 'nordcal-tek-c8b69',
    authDomain: 'nordcal-tek-c8b69.firebaseapp.com',
    databaseURL: 'https://nordcal-tek-c8b69-default-rtdb.firebaseio.com',
    storageBucket: 'nordcal-tek-c8b69.appspot.com',
    measurementId: 'G-FX5GGEK1TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ3Ku2_Ez3tJEUz6ySL-79dEoANYEXAyo',
    appId: '1:616490055606:android:9f5b92860ec12be37f7317',
    messagingSenderId: '616490055606',
    projectId: 'nordcal-tek-c8b69',
    databaseURL: 'https://nordcal-tek-c8b69-default-rtdb.firebaseio.com',
    storageBucket: 'nordcal-tek-c8b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtMThYCGDdSy3PQ8hM-eZ96o3n0TyW6Yc',
    appId: '1:616490055606:ios:1ac850e90c5df88e7f7317',
    messagingSenderId: '616490055606',
    projectId: 'nordcal-tek-c8b69',
    databaseURL: 'https://nordcal-tek-c8b69-default-rtdb.firebaseio.com',
    storageBucket: 'nordcal-tek-c8b69.appspot.com',
    androidClientId: '616490055606-9s3ttagdhagp6it1chhrjj0b5crah40r.apps.googleusercontent.com',
    iosClientId: '616490055606-6h0i59htlnnpkd6k61ks10ca15damceu.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskouPro',
  );
}
